// Code generated by mockery v1.0.1. DO NOT EDIT.

package mocks

import (
	core "github.com/lyft/flyteplugins/go/tasks/pluginmachinery/core"
	mock "github.com/stretchr/testify/mock"

	promutils "github.com/lyft/flytestdlib/promutils"
)

// PluginSetupContext is an autogenerated mock type for the PluginSetupContext type
type PluginSetupContext struct {
	mock.Mock
}

type PluginSetupContext_MetricsScope struct {
	*mock.Call
}

func (_m PluginSetupContext_MetricsScope) Return(_a0 promutils.Scope) *PluginSetupContext_MetricsScope {
	return &PluginSetupContext_MetricsScope{Call: _m.Call.Return(_a0)}
}

func (_m *PluginSetupContext) OnMetricsScope() *PluginSetupContext_MetricsScope {
	c := _m.On("MetricsScope")
	return &PluginSetupContext_MetricsScope{Call: c}
}

func (_m *PluginSetupContext) OnMetricsScopeMatch(matchers ...interface{}) *PluginSetupContext_MetricsScope {
	c := _m.On("MetricsScope", matchers...)
	return &PluginSetupContext_MetricsScope{Call: c}
}

// MetricsScope provides a mock function with given fields:
func (_m *PluginSetupContext) MetricsScope() promutils.Scope {
	ret := _m.Called()

	var r0 promutils.Scope
	if rf, ok := ret.Get(0).(func() promutils.Scope); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(promutils.Scope)
		}
	}

	return r0
}

type PluginSetupContext_SecretManager struct {
	*mock.Call
}

func (_m PluginSetupContext_SecretManager) Return(_a0 core.SecretManager) *PluginSetupContext_SecretManager {
	return &PluginSetupContext_SecretManager{Call: _m.Call.Return(_a0)}
}

func (_m *PluginSetupContext) OnSecretManager() *PluginSetupContext_SecretManager {
	c := _m.On("SecretManager")
	return &PluginSetupContext_SecretManager{Call: c}
}

func (_m *PluginSetupContext) OnSecretManagerMatch(matchers ...interface{}) *PluginSetupContext_SecretManager {
	c := _m.On("SecretManager", matchers...)
	return &PluginSetupContext_SecretManager{Call: c}
}

// SecretManager provides a mock function with given fields:
func (_m *PluginSetupContext) SecretManager() core.SecretManager {
	ret := _m.Called()

	var r0 core.SecretManager
	if rf, ok := ret.Get(0).(func() core.SecretManager); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(core.SecretManager)
		}
	}

	return r0
}
