// Code generated by mockery v1.0.1. DO NOT EDIT.

package mocks

import (
	core "github.com/lyft/flyteplugins/go/tasks/pluginmachinery/core"
	io "github.com/lyft/flyteplugins/go/tasks/pluginmachinery/io"

	mock "github.com/stretchr/testify/mock"
)

// StatusContext is an autogenerated mock type for the StatusContext type
type StatusContext struct {
	mock.Mock
}

type StatusContext_InputReader struct {
	*mock.Call
}

func (_m StatusContext_InputReader) Return(_a0 io.InputReader) *StatusContext_InputReader {
	return &StatusContext_InputReader{Call: _m.Call.Return(_a0)}
}

func (_m *StatusContext) OnInputReader() *StatusContext_InputReader {
	c := _m.On("InputReader")
	return &StatusContext_InputReader{Call: c}
}

func (_m *StatusContext) OnInputReaderMatch(matchers ...interface{}) *StatusContext_InputReader {
	c := _m.On("InputReader", matchers...)
	return &StatusContext_InputReader{Call: c}
}

// InputReader provides a mock function with given fields:
func (_m *StatusContext) InputReader() io.InputReader {
	ret := _m.Called()

	var r0 io.InputReader
	if rf, ok := ret.Get(0).(func() io.InputReader); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(io.InputReader)
		}
	}

	return r0
}

type StatusContext_OutputWriter struct {
	*mock.Call
}

func (_m StatusContext_OutputWriter) Return(_a0 io.OutputWriter) *StatusContext_OutputWriter {
	return &StatusContext_OutputWriter{Call: _m.Call.Return(_a0)}
}

func (_m *StatusContext) OnOutputWriter() *StatusContext_OutputWriter {
	c := _m.On("OutputWriter")
	return &StatusContext_OutputWriter{Call: c}
}

func (_m *StatusContext) OnOutputWriterMatch(matchers ...interface{}) *StatusContext_OutputWriter {
	c := _m.On("OutputWriter", matchers...)
	return &StatusContext_OutputWriter{Call: c}
}

// OutputWriter provides a mock function with given fields:
func (_m *StatusContext) OutputWriter() io.OutputWriter {
	ret := _m.Called()

	var r0 io.OutputWriter
	if rf, ok := ret.Get(0).(func() io.OutputWriter); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(io.OutputWriter)
		}
	}

	return r0
}

type StatusContext_Resource struct {
	*mock.Call
}

func (_m StatusContext_Resource) Return(_a0 interface{}) *StatusContext_Resource {
	return &StatusContext_Resource{Call: _m.Call.Return(_a0)}
}

func (_m *StatusContext) OnResource() *StatusContext_Resource {
	c := _m.On("Resource")
	return &StatusContext_Resource{Call: c}
}

func (_m *StatusContext) OnResourceMatch(matchers ...interface{}) *StatusContext_Resource {
	c := _m.On("Resource", matchers...)
	return &StatusContext_Resource{Call: c}
}

// Resource provides a mock function with given fields:
func (_m *StatusContext) Resource() interface{} {
	ret := _m.Called()

	var r0 interface{}
	if rf, ok := ret.Get(0).(func() interface{}); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}

	return r0
}

type StatusContext_ResourceMeta struct {
	*mock.Call
}

func (_m StatusContext_ResourceMeta) Return(_a0 interface{}) *StatusContext_ResourceMeta {
	return &StatusContext_ResourceMeta{Call: _m.Call.Return(_a0)}
}

func (_m *StatusContext) OnResourceMeta() *StatusContext_ResourceMeta {
	c := _m.On("ResourceMeta")
	return &StatusContext_ResourceMeta{Call: c}
}

func (_m *StatusContext) OnResourceMetaMatch(matchers ...interface{}) *StatusContext_ResourceMeta {
	c := _m.On("ResourceMeta", matchers...)
	return &StatusContext_ResourceMeta{Call: c}
}

// ResourceMeta provides a mock function with given fields:
func (_m *StatusContext) ResourceMeta() interface{} {
	ret := _m.Called()

	var r0 interface{}
	if rf, ok := ret.Get(0).(func() interface{}); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}

	return r0
}

type StatusContext_TaskExecutionMetadata struct {
	*mock.Call
}

func (_m StatusContext_TaskExecutionMetadata) Return(_a0 core.TaskExecutionMetadata) *StatusContext_TaskExecutionMetadata {
	return &StatusContext_TaskExecutionMetadata{Call: _m.Call.Return(_a0)}
}

func (_m *StatusContext) OnTaskExecutionMetadata() *StatusContext_TaskExecutionMetadata {
	c := _m.On("TaskExecutionMetadata")
	return &StatusContext_TaskExecutionMetadata{Call: c}
}

func (_m *StatusContext) OnTaskExecutionMetadataMatch(matchers ...interface{}) *StatusContext_TaskExecutionMetadata {
	c := _m.On("TaskExecutionMetadata", matchers...)
	return &StatusContext_TaskExecutionMetadata{Call: c}
}

// TaskExecutionMetadata provides a mock function with given fields:
func (_m *StatusContext) TaskExecutionMetadata() core.TaskExecutionMetadata {
	ret := _m.Called()

	var r0 core.TaskExecutionMetadata
	if rf, ok := ret.Get(0).(func() core.TaskExecutionMetadata); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(core.TaskExecutionMetadata)
		}
	}

	return r0
}

type StatusContext_TaskReader struct {
	*mock.Call
}

func (_m StatusContext_TaskReader) Return(_a0 core.TaskReader) *StatusContext_TaskReader {
	return &StatusContext_TaskReader{Call: _m.Call.Return(_a0)}
}

func (_m *StatusContext) OnTaskReader() *StatusContext_TaskReader {
	c := _m.On("TaskReader")
	return &StatusContext_TaskReader{Call: c}
}

func (_m *StatusContext) OnTaskReaderMatch(matchers ...interface{}) *StatusContext_TaskReader {
	c := _m.On("TaskReader", matchers...)
	return &StatusContext_TaskReader{Call: c}
}

// TaskReader provides a mock function with given fields:
func (_m *StatusContext) TaskReader() core.TaskReader {
	ret := _m.Called()

	var r0 core.TaskReader
	if rf, ok := ret.Get(0).(func() core.TaskReader); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(core.TaskReader)
		}
	}

	return r0
}
