sudo: required
language: go
go:
- '1.13'
jobs:
  include:
  - stage: test
    name: unit tests and coverage
    install: make install
    script: make test_unit
  - stage: test
    name: benchmark tests
    install: make install
    script: make test_benchmark
  - stage: test
    install: make install
    name: lint
    script: make lint
