// Code generated by mockery v1.0.1. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Resource is an autogenerated mock type for the Resource type
type Resource struct {
	mock.Mock
}
