// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots.

package spark

import (
	"encoding/json"
	"fmt"
	"reflect"
	"strings"
	"testing"

	"github.com/mitchellh/mapstructure"
	"github.com/stretchr/testify/assert"
)

var dereferencableKindsConfig = map[reflect.Kind]struct{}{
	reflect.Array: {}, reflect.Chan: {}, reflect.Map: {}, reflect.Ptr: {}, reflect.Slice: {},
}

// Checks if t is a kind that can be dereferenced to get its underlying type.
func canGetElementConfig(t reflect.Kind) bool {
	_, exists := dereferencableKindsConfig[t]
	return exists
}

// This decoder hook tests types for json unmarshaling capability. If implemented, it uses json unmarshal to build the
// object. Otherwise, it'll just pass on the original data.
func jsonUnmarshalerHookConfig(_, to reflect.Type, data interface{}) (interface{}, error) {
	unmarshalerType := reflect.TypeOf((*json.Unmarshaler)(nil)).Elem()
	if to.Implements(unmarshalerType) || reflect.PtrTo(to).Implements(unmarshalerType) ||
		(canGetElementConfig(to.Kind()) && to.Elem().Implements(unmarshalerType)) {

		raw, err := json.Marshal(data)
		if err != nil {
			fmt.Printf("Failed to marshal Data: %v. Error: %v. Skipping jsonUnmarshalHook", data, err)
			return data, nil
		}

		res := reflect.New(to).Interface()
		err = json.Unmarshal(raw, &res)
		if err != nil {
			fmt.Printf("Failed to umarshal Data: %v. Error: %v. Skipping jsonUnmarshalHook", data, err)
			return data, nil
		}

		return res, nil
	}

	return data, nil
}

func decode_Config(input, result interface{}) error {
	config := &mapstructure.DecoderConfig{
		TagName:          "json",
		WeaklyTypedInput: true,
		Result:           result,
		DecodeHook: mapstructure.ComposeDecodeHookFunc(
			mapstructure.StringToTimeDurationHookFunc(),
			mapstructure.StringToSliceHookFunc(","),
			jsonUnmarshalerHookConfig,
		),
	}

	decoder, err := mapstructure.NewDecoder(config)
	if err != nil {
		return err
	}

	return decoder.Decode(input)
}

func join_Config(arr interface{}, sep string) string {
	listValue := reflect.ValueOf(arr)
	strs := make([]string, 0, listValue.Len())
	for i := 0; i < listValue.Len(); i++ {
		strs = append(strs, fmt.Sprintf("%v", listValue.Index(i)))
	}

	return strings.Join(strs, sep)
}

func testDecodeJson_Config(t *testing.T, val, result interface{}) {
	assert.NoError(t, decode_Config(val, result))
}

func testDecodeSlice_Config(t *testing.T, vStringSlice, result interface{}) {
	assert.NoError(t, decode_Config(vStringSlice, result))
}

func TestConfig_GetPFlagSet(t *testing.T) {
	val := Config{}
	cmdFlags := val.GetPFlagSet("")
	assert.True(t, cmdFlags.HasFlags())
}

func TestConfig_SetFlags(t *testing.T) {
	actual := Config{}
	cmdFlags := actual.GetPFlagSet("")
	assert.True(t, cmdFlags.HasFlags())

	t.Run("Test_spark-history-server-url", func(t *testing.T) {
		t.Run("DefaultValue", func(t *testing.T) {
			// Test that default value is set properly
			if vString, err := cmdFlags.GetString("spark-history-server-url"); err == nil {
				assert.Equal(t, string(defaultConfig.SparkHistoryServerURL), vString)
			} else {
				assert.FailNow(t, err.Error())
			}
		})

		t.Run("Override", func(t *testing.T) {
			testValue := "1"

			cmdFlags.Set("spark-history-server-url", testValue)
			if vString, err := cmdFlags.GetString("spark-history-server-url"); err == nil {
				testDecodeJson_Config(t, fmt.Sprintf("%v", vString), &actual.SparkHistoryServerURL)

			} else {
				assert.FailNow(t, err.Error())
			}
		})
	})
	t.Run("Test_logs.UserLogs.cloudwatch-enabled", func(t *testing.T) {
		t.Run("DefaultValue", func(t *testing.T) {
			// Test that default value is set properly
			if vBool, err := cmdFlags.GetBool("logs.UserLogs.cloudwatch-enabled"); err == nil {
				assert.Equal(t, bool(defaultConfig.LogConfig.UserLogs.IsCloudwatchEnabled), vBool)
			} else {
				assert.FailNow(t, err.Error())
			}
		})

		t.Run("Override", func(t *testing.T) {
			testValue := "1"

			cmdFlags.Set("logs.UserLogs.cloudwatch-enabled", testValue)
			if vBool, err := cmdFlags.GetBool("logs.UserLogs.cloudwatch-enabled"); err == nil {
				testDecodeJson_Config(t, fmt.Sprintf("%v", vBool), &actual.LogConfig.UserLogs.IsCloudwatchEnabled)

			} else {
				assert.FailNow(t, err.Error())
			}
		})
	})
	t.Run("Test_logs.UserLogs.cloudwatch-region", func(t *testing.T) {
		t.Run("DefaultValue", func(t *testing.T) {
			// Test that default value is set properly
			if vString, err := cmdFlags.GetString("logs.UserLogs.cloudwatch-region"); err == nil {
				assert.Equal(t, string(defaultConfig.LogConfig.UserLogs.CloudwatchRegion), vString)
			} else {
				assert.FailNow(t, err.Error())
			}
		})

		t.Run("Override", func(t *testing.T) {
			testValue := "1"

			cmdFlags.Set("logs.UserLogs.cloudwatch-region", testValue)
			if vString, err := cmdFlags.GetString("logs.UserLogs.cloudwatch-region"); err == nil {
				testDecodeJson_Config(t, fmt.Sprintf("%v", vString), &actual.LogConfig.UserLogs.CloudwatchRegion)

			} else {
				assert.FailNow(t, err.Error())
			}
		})
	})
	t.Run("Test_logs.UserLogs.cloudwatch-log-group", func(t *testing.T) {
		t.Run("DefaultValue", func(t *testing.T) {
			// Test that default value is set properly
			if vString, err := cmdFlags.GetString("logs.UserLogs.cloudwatch-log-group"); err == nil {
				assert.Equal(t, string(defaultConfig.LogConfig.UserLogs.CloudwatchLogGroup), vString)
			} else {
				assert.FailNow(t, err.Error())
			}
		})

		t.Run("Override", func(t *testing.T) {
			testValue := "1"

			cmdFlags.Set("logs.UserLogs.cloudwatch-log-group", testValue)
			if vString, err := cmdFlags.GetString("logs.UserLogs.cloudwatch-log-group"); err == nil {
				testDecodeJson_Config(t, fmt.Sprintf("%v", vString), &actual.LogConfig.UserLogs.CloudwatchLogGroup)

			} else {
				assert.FailNow(t, err.Error())
			}
		})
	})
	t.Run("Test_logs.UserLogs.cloudwatch-template-uri", func(t *testing.T) {
		t.Run("DefaultValue", func(t *testing.T) {
			// Test that default value is set properly
			if vString, err := cmdFlags.GetString("logs.UserLogs.cloudwatch-template-uri"); err == nil {
				assert.Equal(t, string(defaultConfig.LogConfig.UserLogs.CloudwatchTemplateURI), vString)
			} else {
				assert.FailNow(t, err.Error())
			}
		})

		t.Run("Override", func(t *testing.T) {
			testValue := "1"

			cmdFlags.Set("logs.UserLogs.cloudwatch-template-uri", testValue)
			if vString, err := cmdFlags.GetString("logs.UserLogs.cloudwatch-template-uri"); err == nil {
				testDecodeJson_Config(t, fmt.Sprintf("%v", vString), &actual.LogConfig.UserLogs.CloudwatchTemplateURI)

			} else {
				assert.FailNow(t, err.Error())
			}
		})
	})
	t.Run("Test_logs.UserLogs.kubernetes-enabled", func(t *testing.T) {
		t.Run("DefaultValue", func(t *testing.T) {
			// Test that default value is set properly
			if vBool, err := cmdFlags.GetBool("logs.UserLogs.kubernetes-enabled"); err == nil {
				assert.Equal(t, bool(defaultConfig.LogConfig.UserLogs.IsKubernetesEnabled), vBool)
			} else {
				assert.FailNow(t, err.Error())
			}
		})

		t.Run("Override", func(t *testing.T) {
			testValue := "1"

			cmdFlags.Set("logs.UserLogs.kubernetes-enabled", testValue)
			if vBool, err := cmdFlags.GetBool("logs.UserLogs.kubernetes-enabled"); err == nil {
				testDecodeJson_Config(t, fmt.Sprintf("%v", vBool), &actual.LogConfig.UserLogs.IsKubernetesEnabled)

			} else {
				assert.FailNow(t, err.Error())
			}
		})
	})
	t.Run("Test_logs.UserLogs.kubernetes-url", func(t *testing.T) {
		t.Run("DefaultValue", func(t *testing.T) {
			// Test that default value is set properly
			if vString, err := cmdFlags.GetString("logs.UserLogs.kubernetes-url"); err == nil {
				assert.Equal(t, string(defaultConfig.LogConfig.UserLogs.KubernetesURL), vString)
			} else {
				assert.FailNow(t, err.Error())
			}
		})

		t.Run("Override", func(t *testing.T) {
			testValue := "1"

			cmdFlags.Set("logs.UserLogs.kubernetes-url", testValue)
			if vString, err := cmdFlags.GetString("logs.UserLogs.kubernetes-url"); err == nil {
				testDecodeJson_Config(t, fmt.Sprintf("%v", vString), &actual.LogConfig.UserLogs.KubernetesURL)

			} else {
				assert.FailNow(t, err.Error())
			}
		})
	})
	t.Run("Test_logs.UserLogs.kubernetes-template-uri", func(t *testing.T) {
		t.Run("DefaultValue", func(t *testing.T) {
			// Test that default value is set properly
			if vString, err := cmdFlags.GetString("logs.UserLogs.kubernetes-template-uri"); err == nil {
				assert.Equal(t, string(defaultConfig.LogConfig.UserLogs.KubernetesTemplateURI), vString)
			} else {
				assert.FailNow(t, err.Error())
			}
		})

		t.Run("Override", func(t *testing.T) {
			testValue := "1"

			cmdFlags.Set("logs.UserLogs.kubernetes-template-uri", testValue)
			if vString, err := cmdFlags.GetString("logs.UserLogs.kubernetes-template-uri"); err == nil {
				testDecodeJson_Config(t, fmt.Sprintf("%v", vString), &actual.LogConfig.UserLogs.KubernetesTemplateURI)

			} else {
				assert.FailNow(t, err.Error())
			}
		})
	})
	t.Run("Test_logs.UserLogs.stackdriver-enabled", func(t *testing.T) {
		t.Run("DefaultValue", func(t *testing.T) {
			// Test that default value is set properly
			if vBool, err := cmdFlags.GetBool("logs.UserLogs.stackdriver-enabled"); err == nil {
				assert.Equal(t, bool(defaultConfig.LogConfig.UserLogs.IsStackDriverEnabled), vBool)
			} else {
				assert.FailNow(t, err.Error())
			}
		})

		t.Run("Override", func(t *testing.T) {
			testValue := "1"

			cmdFlags.Set("logs.UserLogs.stackdriver-enabled", testValue)
			if vBool, err := cmdFlags.GetBool("logs.UserLogs.stackdriver-enabled"); err == nil {
				testDecodeJson_Config(t, fmt.Sprintf("%v", vBool), &actual.LogConfig.UserLogs.IsStackDriverEnabled)

			} else {
				assert.FailNow(t, err.Error())
			}
		})
	})
	t.Run("Test_logs.UserLogs.gcp-project", func(t *testing.T) {
		t.Run("DefaultValue", func(t *testing.T) {
			// Test that default value is set properly
			if vString, err := cmdFlags.GetString("logs.UserLogs.gcp-project"); err == nil {
				assert.Equal(t, string(defaultConfig.LogConfig.UserLogs.GCPProjectName), vString)
			} else {
				assert.FailNow(t, err.Error())
			}
		})

		t.Run("Override", func(t *testing.T) {
			testValue := "1"

			cmdFlags.Set("logs.UserLogs.gcp-project", testValue)
			if vString, err := cmdFlags.GetString("logs.UserLogs.gcp-project"); err == nil {
				testDecodeJson_Config(t, fmt.Sprintf("%v", vString), &actual.LogConfig.UserLogs.GCPProjectName)

			} else {
				assert.FailNow(t, err.Error())
			}
		})
	})
	t.Run("Test_logs.UserLogs.stackdriver-logresourcename", func(t *testing.T) {
		t.Run("DefaultValue", func(t *testing.T) {
			// Test that default value is set properly
			if vString, err := cmdFlags.GetString("logs.UserLogs.stackdriver-logresourcename"); err == nil {
				assert.Equal(t, string(defaultConfig.LogConfig.UserLogs.StackdriverLogResourceName), vString)
			} else {
				assert.FailNow(t, err.Error())
			}
		})

		t.Run("Override", func(t *testing.T) {
			testValue := "1"

			cmdFlags.Set("logs.UserLogs.stackdriver-logresourcename", testValue)
			if vString, err := cmdFlags.GetString("logs.UserLogs.stackdriver-logresourcename"); err == nil {
				testDecodeJson_Config(t, fmt.Sprintf("%v", vString), &actual.LogConfig.UserLogs.StackdriverLogResourceName)

			} else {
				assert.FailNow(t, err.Error())
			}
		})
	})
	t.Run("Test_logs.UserLogs.stackdriver-template-uri", func(t *testing.T) {
		t.Run("DefaultValue", func(t *testing.T) {
			// Test that default value is set properly
			if vString, err := cmdFlags.GetString("logs.UserLogs.stackdriver-template-uri"); err == nil {
				assert.Equal(t, string(defaultConfig.LogConfig.UserLogs.StackDriverTemplateURI), vString)
			} else {
				assert.FailNow(t, err.Error())
			}
		})

		t.Run("Override", func(t *testing.T) {
			testValue := "1"

			cmdFlags.Set("logs.UserLogs.stackdriver-template-uri", testValue)
			if vString, err := cmdFlags.GetString("logs.UserLogs.stackdriver-template-uri"); err == nil {
				testDecodeJson_Config(t, fmt.Sprintf("%v", vString), &actual.LogConfig.UserLogs.StackDriverTemplateURI)

			} else {
				assert.FailNow(t, err.Error())
			}
		})
	})
	t.Run("Test_logs.SystemLogs.cloudwatch-enabled", func(t *testing.T) {
		t.Run("DefaultValue", func(t *testing.T) {
			// Test that default value is set properly
			if vBool, err := cmdFlags.GetBool("logs.SystemLogs.cloudwatch-enabled"); err == nil {
				assert.Equal(t, bool(defaultConfig.LogConfig.SystemLogs.IsCloudwatchEnabled), vBool)
			} else {
				assert.FailNow(t, err.Error())
			}
		})

		t.Run("Override", func(t *testing.T) {
			testValue := "1"

			cmdFlags.Set("logs.SystemLogs.cloudwatch-enabled", testValue)
			if vBool, err := cmdFlags.GetBool("logs.SystemLogs.cloudwatch-enabled"); err == nil {
				testDecodeJson_Config(t, fmt.Sprintf("%v", vBool), &actual.LogConfig.SystemLogs.IsCloudwatchEnabled)

			} else {
				assert.FailNow(t, err.Error())
			}
		})
	})
	t.Run("Test_logs.SystemLogs.cloudwatch-region", func(t *testing.T) {
		t.Run("DefaultValue", func(t *testing.T) {
			// Test that default value is set properly
			if vString, err := cmdFlags.GetString("logs.SystemLogs.cloudwatch-region"); err == nil {
				assert.Equal(t, string(defaultConfig.LogConfig.SystemLogs.CloudwatchRegion), vString)
			} else {
				assert.FailNow(t, err.Error())
			}
		})

		t.Run("Override", func(t *testing.T) {
			testValue := "1"

			cmdFlags.Set("logs.SystemLogs.cloudwatch-region", testValue)
			if vString, err := cmdFlags.GetString("logs.SystemLogs.cloudwatch-region"); err == nil {
				testDecodeJson_Config(t, fmt.Sprintf("%v", vString), &actual.LogConfig.SystemLogs.CloudwatchRegion)

			} else {
				assert.FailNow(t, err.Error())
			}
		})
	})
	t.Run("Test_logs.SystemLogs.cloudwatch-log-group", func(t *testing.T) {
		t.Run("DefaultValue", func(t *testing.T) {
			// Test that default value is set properly
			if vString, err := cmdFlags.GetString("logs.SystemLogs.cloudwatch-log-group"); err == nil {
				assert.Equal(t, string(defaultConfig.LogConfig.SystemLogs.CloudwatchLogGroup), vString)
			} else {
				assert.FailNow(t, err.Error())
			}
		})

		t.Run("Override", func(t *testing.T) {
			testValue := "1"

			cmdFlags.Set("logs.SystemLogs.cloudwatch-log-group", testValue)
			if vString, err := cmdFlags.GetString("logs.SystemLogs.cloudwatch-log-group"); err == nil {
				testDecodeJson_Config(t, fmt.Sprintf("%v", vString), &actual.LogConfig.SystemLogs.CloudwatchLogGroup)

			} else {
				assert.FailNow(t, err.Error())
			}
		})
	})
	t.Run("Test_logs.SystemLogs.cloudwatch-template-uri", func(t *testing.T) {
		t.Run("DefaultValue", func(t *testing.T) {
			// Test that default value is set properly
			if vString, err := cmdFlags.GetString("logs.SystemLogs.cloudwatch-template-uri"); err == nil {
				assert.Equal(t, string(defaultConfig.LogConfig.SystemLogs.CloudwatchTemplateURI), vString)
			} else {
				assert.FailNow(t, err.Error())
			}
		})

		t.Run("Override", func(t *testing.T) {
			testValue := "1"

			cmdFlags.Set("logs.SystemLogs.cloudwatch-template-uri", testValue)
			if vString, err := cmdFlags.GetString("logs.SystemLogs.cloudwatch-template-uri"); err == nil {
				testDecodeJson_Config(t, fmt.Sprintf("%v", vString), &actual.LogConfig.SystemLogs.CloudwatchTemplateURI)

			} else {
				assert.FailNow(t, err.Error())
			}
		})
	})
	t.Run("Test_logs.SystemLogs.kubernetes-enabled", func(t *testing.T) {
		t.Run("DefaultValue", func(t *testing.T) {
			// Test that default value is set properly
			if vBool, err := cmdFlags.GetBool("logs.SystemLogs.kubernetes-enabled"); err == nil {
				assert.Equal(t, bool(defaultConfig.LogConfig.SystemLogs.IsKubernetesEnabled), vBool)
			} else {
				assert.FailNow(t, err.Error())
			}
		})

		t.Run("Override", func(t *testing.T) {
			testValue := "1"

			cmdFlags.Set("logs.SystemLogs.kubernetes-enabled", testValue)
			if vBool, err := cmdFlags.GetBool("logs.SystemLogs.kubernetes-enabled"); err == nil {
				testDecodeJson_Config(t, fmt.Sprintf("%v", vBool), &actual.LogConfig.SystemLogs.IsKubernetesEnabled)

			} else {
				assert.FailNow(t, err.Error())
			}
		})
	})
	t.Run("Test_logs.SystemLogs.kubernetes-url", func(t *testing.T) {
		t.Run("DefaultValue", func(t *testing.T) {
			// Test that default value is set properly
			if vString, err := cmdFlags.GetString("logs.SystemLogs.kubernetes-url"); err == nil {
				assert.Equal(t, string(defaultConfig.LogConfig.SystemLogs.KubernetesURL), vString)
			} else {
				assert.FailNow(t, err.Error())
			}
		})

		t.Run("Override", func(t *testing.T) {
			testValue := "1"

			cmdFlags.Set("logs.SystemLogs.kubernetes-url", testValue)
			if vString, err := cmdFlags.GetString("logs.SystemLogs.kubernetes-url"); err == nil {
				testDecodeJson_Config(t, fmt.Sprintf("%v", vString), &actual.LogConfig.SystemLogs.KubernetesURL)

			} else {
				assert.FailNow(t, err.Error())
			}
		})
	})
	t.Run("Test_logs.SystemLogs.kubernetes-template-uri", func(t *testing.T) {
		t.Run("DefaultValue", func(t *testing.T) {
			// Test that default value is set properly
			if vString, err := cmdFlags.GetString("logs.SystemLogs.kubernetes-template-uri"); err == nil {
				assert.Equal(t, string(defaultConfig.LogConfig.SystemLogs.KubernetesTemplateURI), vString)
			} else {
				assert.FailNow(t, err.Error())
			}
		})

		t.Run("Override", func(t *testing.T) {
			testValue := "1"

			cmdFlags.Set("logs.SystemLogs.kubernetes-template-uri", testValue)
			if vString, err := cmdFlags.GetString("logs.SystemLogs.kubernetes-template-uri"); err == nil {
				testDecodeJson_Config(t, fmt.Sprintf("%v", vString), &actual.LogConfig.SystemLogs.KubernetesTemplateURI)

			} else {
				assert.FailNow(t, err.Error())
			}
		})
	})
	t.Run("Test_logs.SystemLogs.stackdriver-enabled", func(t *testing.T) {
		t.Run("DefaultValue", func(t *testing.T) {
			// Test that default value is set properly
			if vBool, err := cmdFlags.GetBool("logs.SystemLogs.stackdriver-enabled"); err == nil {
				assert.Equal(t, bool(defaultConfig.LogConfig.SystemLogs.IsStackDriverEnabled), vBool)
			} else {
				assert.FailNow(t, err.Error())
			}
		})

		t.Run("Override", func(t *testing.T) {
			testValue := "1"

			cmdFlags.Set("logs.SystemLogs.stackdriver-enabled", testValue)
			if vBool, err := cmdFlags.GetBool("logs.SystemLogs.stackdriver-enabled"); err == nil {
				testDecodeJson_Config(t, fmt.Sprintf("%v", vBool), &actual.LogConfig.SystemLogs.IsStackDriverEnabled)

			} else {
				assert.FailNow(t, err.Error())
			}
		})
	})
	t.Run("Test_logs.SystemLogs.gcp-project", func(t *testing.T) {
		t.Run("DefaultValue", func(t *testing.T) {
			// Test that default value is set properly
			if vString, err := cmdFlags.GetString("logs.SystemLogs.gcp-project"); err == nil {
				assert.Equal(t, string(defaultConfig.LogConfig.SystemLogs.GCPProjectName), vString)
			} else {
				assert.FailNow(t, err.Error())
			}
		})

		t.Run("Override", func(t *testing.T) {
			testValue := "1"

			cmdFlags.Set("logs.SystemLogs.gcp-project", testValue)
			if vString, err := cmdFlags.GetString("logs.SystemLogs.gcp-project"); err == nil {
				testDecodeJson_Config(t, fmt.Sprintf("%v", vString), &actual.LogConfig.SystemLogs.GCPProjectName)

			} else {
				assert.FailNow(t, err.Error())
			}
		})
	})
	t.Run("Test_logs.SystemLogs.stackdriver-logresourcename", func(t *testing.T) {
		t.Run("DefaultValue", func(t *testing.T) {
			// Test that default value is set properly
			if vString, err := cmdFlags.GetString("logs.SystemLogs.stackdriver-logresourcename"); err == nil {
				assert.Equal(t, string(defaultConfig.LogConfig.SystemLogs.StackdriverLogResourceName), vString)
			} else {
				assert.FailNow(t, err.Error())
			}
		})

		t.Run("Override", func(t *testing.T) {
			testValue := "1"

			cmdFlags.Set("logs.SystemLogs.stackdriver-logresourcename", testValue)
			if vString, err := cmdFlags.GetString("logs.SystemLogs.stackdriver-logresourcename"); err == nil {
				testDecodeJson_Config(t, fmt.Sprintf("%v", vString), &actual.LogConfig.SystemLogs.StackdriverLogResourceName)

			} else {
				assert.FailNow(t, err.Error())
			}
		})
	})
	t.Run("Test_logs.SystemLogs.stackdriver-template-uri", func(t *testing.T) {
		t.Run("DefaultValue", func(t *testing.T) {
			// Test that default value is set properly
			if vString, err := cmdFlags.GetString("logs.SystemLogs.stackdriver-template-uri"); err == nil {
				assert.Equal(t, string(defaultConfig.LogConfig.SystemLogs.StackDriverTemplateURI), vString)
			} else {
				assert.FailNow(t, err.Error())
			}
		})

		t.Run("Override", func(t *testing.T) {
			testValue := "1"

			cmdFlags.Set("logs.SystemLogs.stackdriver-template-uri", testValue)
			if vString, err := cmdFlags.GetString("logs.SystemLogs.stackdriver-template-uri"); err == nil {
				testDecodeJson_Config(t, fmt.Sprintf("%v", vString), &actual.LogConfig.SystemLogs.StackDriverTemplateURI)

			} else {
				assert.FailNow(t, err.Error())
			}
		})
	})
	t.Run("Test_logs.AllUserLogs.cloudwatch-enabled", func(t *testing.T) {
		t.Run("DefaultValue", func(t *testing.T) {
			// Test that default value is set properly
			if vBool, err := cmdFlags.GetBool("logs.AllUserLogs.cloudwatch-enabled"); err == nil {
				assert.Equal(t, bool(defaultConfig.LogConfig.AllUserLogs.IsCloudwatchEnabled), vBool)
			} else {
				assert.FailNow(t, err.Error())
			}
		})

		t.Run("Override", func(t *testing.T) {
			testValue := "1"

			cmdFlags.Set("logs.AllUserLogs.cloudwatch-enabled", testValue)
			if vBool, err := cmdFlags.GetBool("logs.AllUserLogs.cloudwatch-enabled"); err == nil {
				testDecodeJson_Config(t, fmt.Sprintf("%v", vBool), &actual.LogConfig.AllUserLogs.IsCloudwatchEnabled)

			} else {
				assert.FailNow(t, err.Error())
			}
		})
	})
	t.Run("Test_logs.AllUserLogs.cloudwatch-region", func(t *testing.T) {
		t.Run("DefaultValue", func(t *testing.T) {
			// Test that default value is set properly
			if vString, err := cmdFlags.GetString("logs.AllUserLogs.cloudwatch-region"); err == nil {
				assert.Equal(t, string(defaultConfig.LogConfig.AllUserLogs.CloudwatchRegion), vString)
			} else {
				assert.FailNow(t, err.Error())
			}
		})

		t.Run("Override", func(t *testing.T) {
			testValue := "1"

			cmdFlags.Set("logs.AllUserLogs.cloudwatch-region", testValue)
			if vString, err := cmdFlags.GetString("logs.AllUserLogs.cloudwatch-region"); err == nil {
				testDecodeJson_Config(t, fmt.Sprintf("%v", vString), &actual.LogConfig.AllUserLogs.CloudwatchRegion)

			} else {
				assert.FailNow(t, err.Error())
			}
		})
	})
	t.Run("Test_logs.AllUserLogs.cloudwatch-log-group", func(t *testing.T) {
		t.Run("DefaultValue", func(t *testing.T) {
			// Test that default value is set properly
			if vString, err := cmdFlags.GetString("logs.AllUserLogs.cloudwatch-log-group"); err == nil {
				assert.Equal(t, string(defaultConfig.LogConfig.AllUserLogs.CloudwatchLogGroup), vString)
			} else {
				assert.FailNow(t, err.Error())
			}
		})

		t.Run("Override", func(t *testing.T) {
			testValue := "1"

			cmdFlags.Set("logs.AllUserLogs.cloudwatch-log-group", testValue)
			if vString, err := cmdFlags.GetString("logs.AllUserLogs.cloudwatch-log-group"); err == nil {
				testDecodeJson_Config(t, fmt.Sprintf("%v", vString), &actual.LogConfig.AllUserLogs.CloudwatchLogGroup)

			} else {
				assert.FailNow(t, err.Error())
			}
		})
	})
	t.Run("Test_logs.AllUserLogs.cloudwatch-template-uri", func(t *testing.T) {
		t.Run("DefaultValue", func(t *testing.T) {
			// Test that default value is set properly
			if vString, err := cmdFlags.GetString("logs.AllUserLogs.cloudwatch-template-uri"); err == nil {
				assert.Equal(t, string(defaultConfig.LogConfig.AllUserLogs.CloudwatchTemplateURI), vString)
			} else {
				assert.FailNow(t, err.Error())
			}
		})

		t.Run("Override", func(t *testing.T) {
			testValue := "1"

			cmdFlags.Set("logs.AllUserLogs.cloudwatch-template-uri", testValue)
			if vString, err := cmdFlags.GetString("logs.AllUserLogs.cloudwatch-template-uri"); err == nil {
				testDecodeJson_Config(t, fmt.Sprintf("%v", vString), &actual.LogConfig.AllUserLogs.CloudwatchTemplateURI)

			} else {
				assert.FailNow(t, err.Error())
			}
		})
	})
	t.Run("Test_logs.AllUserLogs.kubernetes-enabled", func(t *testing.T) {
		t.Run("DefaultValue", func(t *testing.T) {
			// Test that default value is set properly
			if vBool, err := cmdFlags.GetBool("logs.AllUserLogs.kubernetes-enabled"); err == nil {
				assert.Equal(t, bool(defaultConfig.LogConfig.AllUserLogs.IsKubernetesEnabled), vBool)
			} else {
				assert.FailNow(t, err.Error())
			}
		})

		t.Run("Override", func(t *testing.T) {
			testValue := "1"

			cmdFlags.Set("logs.AllUserLogs.kubernetes-enabled", testValue)
			if vBool, err := cmdFlags.GetBool("logs.AllUserLogs.kubernetes-enabled"); err == nil {
				testDecodeJson_Config(t, fmt.Sprintf("%v", vBool), &actual.LogConfig.AllUserLogs.IsKubernetesEnabled)

			} else {
				assert.FailNow(t, err.Error())
			}
		})
	})
	t.Run("Test_logs.AllUserLogs.kubernetes-url", func(t *testing.T) {
		t.Run("DefaultValue", func(t *testing.T) {
			// Test that default value is set properly
			if vString, err := cmdFlags.GetString("logs.AllUserLogs.kubernetes-url"); err == nil {
				assert.Equal(t, string(defaultConfig.LogConfig.AllUserLogs.KubernetesURL), vString)
			} else {
				assert.FailNow(t, err.Error())
			}
		})

		t.Run("Override", func(t *testing.T) {
			testValue := "1"

			cmdFlags.Set("logs.AllUserLogs.kubernetes-url", testValue)
			if vString, err := cmdFlags.GetString("logs.AllUserLogs.kubernetes-url"); err == nil {
				testDecodeJson_Config(t, fmt.Sprintf("%v", vString), &actual.LogConfig.AllUserLogs.KubernetesURL)

			} else {
				assert.FailNow(t, err.Error())
			}
		})
	})
	t.Run("Test_logs.AllUserLogs.kubernetes-template-uri", func(t *testing.T) {
		t.Run("DefaultValue", func(t *testing.T) {
			// Test that default value is set properly
			if vString, err := cmdFlags.GetString("logs.AllUserLogs.kubernetes-template-uri"); err == nil {
				assert.Equal(t, string(defaultConfig.LogConfig.AllUserLogs.KubernetesTemplateURI), vString)
			} else {
				assert.FailNow(t, err.Error())
			}
		})

		t.Run("Override", func(t *testing.T) {
			testValue := "1"

			cmdFlags.Set("logs.AllUserLogs.kubernetes-template-uri", testValue)
			if vString, err := cmdFlags.GetString("logs.AllUserLogs.kubernetes-template-uri"); err == nil {
				testDecodeJson_Config(t, fmt.Sprintf("%v", vString), &actual.LogConfig.AllUserLogs.KubernetesTemplateURI)

			} else {
				assert.FailNow(t, err.Error())
			}
		})
	})
	t.Run("Test_logs.AllUserLogs.stackdriver-enabled", func(t *testing.T) {
		t.Run("DefaultValue", func(t *testing.T) {
			// Test that default value is set properly
			if vBool, err := cmdFlags.GetBool("logs.AllUserLogs.stackdriver-enabled"); err == nil {
				assert.Equal(t, bool(defaultConfig.LogConfig.AllUserLogs.IsStackDriverEnabled), vBool)
			} else {
				assert.FailNow(t, err.Error())
			}
		})

		t.Run("Override", func(t *testing.T) {
			testValue := "1"

			cmdFlags.Set("logs.AllUserLogs.stackdriver-enabled", testValue)
			if vBool, err := cmdFlags.GetBool("logs.AllUserLogs.stackdriver-enabled"); err == nil {
				testDecodeJson_Config(t, fmt.Sprintf("%v", vBool), &actual.LogConfig.AllUserLogs.IsStackDriverEnabled)

			} else {
				assert.FailNow(t, err.Error())
			}
		})
	})
	t.Run("Test_logs.AllUserLogs.gcp-project", func(t *testing.T) {
		t.Run("DefaultValue", func(t *testing.T) {
			// Test that default value is set properly
			if vString, err := cmdFlags.GetString("logs.AllUserLogs.gcp-project"); err == nil {
				assert.Equal(t, string(defaultConfig.LogConfig.AllUserLogs.GCPProjectName), vString)
			} else {
				assert.FailNow(t, err.Error())
			}
		})

		t.Run("Override", func(t *testing.T) {
			testValue := "1"

			cmdFlags.Set("logs.AllUserLogs.gcp-project", testValue)
			if vString, err := cmdFlags.GetString("logs.AllUserLogs.gcp-project"); err == nil {
				testDecodeJson_Config(t, fmt.Sprintf("%v", vString), &actual.LogConfig.AllUserLogs.GCPProjectName)

			} else {
				assert.FailNow(t, err.Error())
			}
		})
	})
	t.Run("Test_logs.AllUserLogs.stackdriver-logresourcename", func(t *testing.T) {
		t.Run("DefaultValue", func(t *testing.T) {
			// Test that default value is set properly
			if vString, err := cmdFlags.GetString("logs.AllUserLogs.stackdriver-logresourcename"); err == nil {
				assert.Equal(t, string(defaultConfig.LogConfig.AllUserLogs.StackdriverLogResourceName), vString)
			} else {
				assert.FailNow(t, err.Error())
			}
		})

		t.Run("Override", func(t *testing.T) {
			testValue := "1"

			cmdFlags.Set("logs.AllUserLogs.stackdriver-logresourcename", testValue)
			if vString, err := cmdFlags.GetString("logs.AllUserLogs.stackdriver-logresourcename"); err == nil {
				testDecodeJson_Config(t, fmt.Sprintf("%v", vString), &actual.LogConfig.AllUserLogs.StackdriverLogResourceName)

			} else {
				assert.FailNow(t, err.Error())
			}
		})
	})
	t.Run("Test_logs.AllUserLogs.stackdriver-template-uri", func(t *testing.T) {
		t.Run("DefaultValue", func(t *testing.T) {
			// Test that default value is set properly
			if vString, err := cmdFlags.GetString("logs.AllUserLogs.stackdriver-template-uri"); err == nil {
				assert.Equal(t, string(defaultConfig.LogConfig.AllUserLogs.StackDriverTemplateURI), vString)
			} else {
				assert.FailNow(t, err.Error())
			}
		})

		t.Run("Override", func(t *testing.T) {
			testValue := "1"

			cmdFlags.Set("logs.AllUserLogs.stackdriver-template-uri", testValue)
			if vString, err := cmdFlags.GetString("logs.AllUserLogs.stackdriver-template-uri"); err == nil {
				testDecodeJson_Config(t, fmt.Sprintf("%v", vString), &actual.LogConfig.AllUserLogs.StackDriverTemplateURI)

			} else {
				assert.FailNow(t, err.Error())
			}
		})
	})
}
