// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots.

package spark

import (
	"encoding/json"
	"reflect"

	"fmt"

	"github.com/spf13/pflag"
)

// If v is a pointer, it will get its element value or the zero value of the element type.
// If v is not a pointer, it will return it as is.
func (Config) elemValueOrNil(v interface{}) interface{} {
	if t := reflect.TypeOf(v); t.Kind() == reflect.Ptr {
		if reflect.ValueOf(v).IsNil() {
			return reflect.Zero(t.Elem()).Interface()
		} else {
			return reflect.ValueOf(v).Interface()
		}
	} else if v == nil {
		return reflect.Zero(t).Interface()
	}

	return v
}

func (Config) mustMarshalJSON(v json.Marshaler) string {
	raw, err := v.MarshalJSON()
	if err != nil {
		panic(err)
	}

	return string(raw)
}

// GetPFlagSet will return strongly types pflags for all fields in Config and its nested types. The format of the
// flags is json-name.json-sub-name... etc.
func (cfg Config) GetPFlagSet(prefix string) *pflag.FlagSet {
	cmdFlags := pflag.NewFlagSet("Config", pflag.ExitOnError)
	cmdFlags.String(fmt.Sprintf("%v%v", prefix, "spark-history-server-url"), defaultConfig.SparkHistoryServerURL, "URL for SparkHistory Server that each job will publish the execution history to.")
	cmdFlags.Bool(fmt.Sprintf("%v%v", prefix, "logs.UserLogs.cloudwatch-enabled"), defaultConfig.LogConfig.UserLogs.IsCloudwatchEnabled, "Enable Cloudwatch Logging")
	cmdFlags.String(fmt.Sprintf("%v%v", prefix, "logs.UserLogs.cloudwatch-region"), defaultConfig.LogConfig.UserLogs.CloudwatchRegion, "AWS region in which Cloudwatch logs are stored.")
	cmdFlags.String(fmt.Sprintf("%v%v", prefix, "logs.UserLogs.cloudwatch-log-group"), defaultConfig.LogConfig.UserLogs.CloudwatchLogGroup, "Log group to which streams are associated.")
	cmdFlags.String(fmt.Sprintf("%v%v", prefix, "logs.UserLogs.cloudwatch-template-uri"), defaultConfig.LogConfig.UserLogs.CloudwatchTemplateURI, "Template Uri to use when building cloudwatch log links")
	cmdFlags.Bool(fmt.Sprintf("%v%v", prefix, "logs.UserLogs.kubernetes-enabled"), defaultConfig.LogConfig.UserLogs.IsKubernetesEnabled, "Enable Kubernetes Logging")
	cmdFlags.String(fmt.Sprintf("%v%v", prefix, "logs.UserLogs.kubernetes-url"), defaultConfig.LogConfig.UserLogs.KubernetesURL, "Console URL for Kubernetes logs")
	cmdFlags.String(fmt.Sprintf("%v%v", prefix, "logs.UserLogs.kubernetes-template-uri"), defaultConfig.LogConfig.UserLogs.KubernetesTemplateURI, "Template Uri to use when building kubernetes log links")
	cmdFlags.Bool(fmt.Sprintf("%v%v", prefix, "logs.UserLogs.stackdriver-enabled"), defaultConfig.LogConfig.UserLogs.IsStackDriverEnabled, "Enable Log-links to stackdriver")
	cmdFlags.String(fmt.Sprintf("%v%v", prefix, "logs.UserLogs.gcp-project"), defaultConfig.LogConfig.UserLogs.GCPProjectName, "Name of the project in GCP")
	cmdFlags.String(fmt.Sprintf("%v%v", prefix, "logs.UserLogs.stackdriver-logresourcename"), defaultConfig.LogConfig.UserLogs.StackdriverLogResourceName, "Name of the logresource in stackdriver")
	cmdFlags.String(fmt.Sprintf("%v%v", prefix, "logs.UserLogs.stackdriver-template-uri"), defaultConfig.LogConfig.UserLogs.StackDriverTemplateURI, "Template Uri to use when building stackdriver log links")
	cmdFlags.Bool(fmt.Sprintf("%v%v", prefix, "logs.SystemLogs.cloudwatch-enabled"), defaultConfig.LogConfig.SystemLogs.IsCloudwatchEnabled, "Enable Cloudwatch Logging")
	cmdFlags.String(fmt.Sprintf("%v%v", prefix, "logs.SystemLogs.cloudwatch-region"), defaultConfig.LogConfig.SystemLogs.CloudwatchRegion, "AWS region in which Cloudwatch logs are stored.")
	cmdFlags.String(fmt.Sprintf("%v%v", prefix, "logs.SystemLogs.cloudwatch-log-group"), defaultConfig.LogConfig.SystemLogs.CloudwatchLogGroup, "Log group to which streams are associated.")
	cmdFlags.String(fmt.Sprintf("%v%v", prefix, "logs.SystemLogs.cloudwatch-template-uri"), defaultConfig.LogConfig.SystemLogs.CloudwatchTemplateURI, "Template Uri to use when building cloudwatch log links")
	cmdFlags.Bool(fmt.Sprintf("%v%v", prefix, "logs.SystemLogs.kubernetes-enabled"), defaultConfig.LogConfig.SystemLogs.IsKubernetesEnabled, "Enable Kubernetes Logging")
	cmdFlags.String(fmt.Sprintf("%v%v", prefix, "logs.SystemLogs.kubernetes-url"), defaultConfig.LogConfig.SystemLogs.KubernetesURL, "Console URL for Kubernetes logs")
	cmdFlags.String(fmt.Sprintf("%v%v", prefix, "logs.SystemLogs.kubernetes-template-uri"), defaultConfig.LogConfig.SystemLogs.KubernetesTemplateURI, "Template Uri to use when building kubernetes log links")
	cmdFlags.Bool(fmt.Sprintf("%v%v", prefix, "logs.SystemLogs.stackdriver-enabled"), defaultConfig.LogConfig.SystemLogs.IsStackDriverEnabled, "Enable Log-links to stackdriver")
	cmdFlags.String(fmt.Sprintf("%v%v", prefix, "logs.SystemLogs.gcp-project"), defaultConfig.LogConfig.SystemLogs.GCPProjectName, "Name of the project in GCP")
	cmdFlags.String(fmt.Sprintf("%v%v", prefix, "logs.SystemLogs.stackdriver-logresourcename"), defaultConfig.LogConfig.SystemLogs.StackdriverLogResourceName, "Name of the logresource in stackdriver")
	cmdFlags.String(fmt.Sprintf("%v%v", prefix, "logs.SystemLogs.stackdriver-template-uri"), defaultConfig.LogConfig.SystemLogs.StackDriverTemplateURI, "Template Uri to use when building stackdriver log links")
	cmdFlags.Bool(fmt.Sprintf("%v%v", prefix, "logs.AllUserLogs.cloudwatch-enabled"), defaultConfig.LogConfig.AllUserLogs.IsCloudwatchEnabled, "Enable Cloudwatch Logging")
	cmdFlags.String(fmt.Sprintf("%v%v", prefix, "logs.AllUserLogs.cloudwatch-region"), defaultConfig.LogConfig.AllUserLogs.CloudwatchRegion, "AWS region in which Cloudwatch logs are stored.")
	cmdFlags.String(fmt.Sprintf("%v%v", prefix, "logs.AllUserLogs.cloudwatch-log-group"), defaultConfig.LogConfig.AllUserLogs.CloudwatchLogGroup, "Log group to which streams are associated.")
	cmdFlags.String(fmt.Sprintf("%v%v", prefix, "logs.AllUserLogs.cloudwatch-template-uri"), defaultConfig.LogConfig.AllUserLogs.CloudwatchTemplateURI, "Template Uri to use when building cloudwatch log links")
	cmdFlags.Bool(fmt.Sprintf("%v%v", prefix, "logs.AllUserLogs.kubernetes-enabled"), defaultConfig.LogConfig.AllUserLogs.IsKubernetesEnabled, "Enable Kubernetes Logging")
	cmdFlags.String(fmt.Sprintf("%v%v", prefix, "logs.AllUserLogs.kubernetes-url"), defaultConfig.LogConfig.AllUserLogs.KubernetesURL, "Console URL for Kubernetes logs")
	cmdFlags.String(fmt.Sprintf("%v%v", prefix, "logs.AllUserLogs.kubernetes-template-uri"), defaultConfig.LogConfig.AllUserLogs.KubernetesTemplateURI, "Template Uri to use when building kubernetes log links")
	cmdFlags.Bool(fmt.Sprintf("%v%v", prefix, "logs.AllUserLogs.stackdriver-enabled"), defaultConfig.LogConfig.AllUserLogs.IsStackDriverEnabled, "Enable Log-links to stackdriver")
	cmdFlags.String(fmt.Sprintf("%v%v", prefix, "logs.AllUserLogs.gcp-project"), defaultConfig.LogConfig.AllUserLogs.GCPProjectName, "Name of the project in GCP")
	cmdFlags.String(fmt.Sprintf("%v%v", prefix, "logs.AllUserLogs.stackdriver-logresourcename"), defaultConfig.LogConfig.AllUserLogs.StackdriverLogResourceName, "Name of the logresource in stackdriver")
	cmdFlags.String(fmt.Sprintf("%v%v", prefix, "logs.AllUserLogs.stackdriver-template-uri"), defaultConfig.LogConfig.AllUserLogs.StackDriverTemplateURI, "Template Uri to use when building stackdriver log links")
	return cmdFlags
}
