// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// PluginStateWriter is an autogenerated mock type for the PluginStateWriter type
type PluginStateWriter struct {
	mock.Mock
}

// Put provides a mock function with given fields: stateVersion, v
func (_m *PluginStateWriter) Put(stateVersion uint8, v interface{}) error {
	ret := _m.Called(stateVersion, v)

	var r0 error
	if rf, ok := ret.Get(0).(func(uint8, interface{}) error); ok {
		r0 = rf(stateVersion, v)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Reset provides a mock function with given fields:
func (_m *PluginStateWriter) Reset() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
