// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// PluginStateReader is an autogenerated mock type for the PluginStateReader type
type PluginStateReader struct {
	mock.Mock
}

// Get provides a mock function with given fields: t
func (_m *PluginStateReader) Get(t interface{}) (uint8, error) {
	ret := _m.Called(t)

	var r0 uint8
	if rf, ok := ret.Get(0).(func(interface{}) uint8); ok {
		r0 = rf(t)
	} else {
		r0 = ret.Get(0).(uint8)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(interface{}) error); ok {
		r1 = rf(t)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetStateVersion provides a mock function with given fields:
func (_m *PluginStateReader) GetStateVersion() uint8 {
	ret := _m.Called()

	var r0 uint8
	if rf, ok := ret.Get(0).(func() uint8); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(uint8)
	}

	return r0
}
