// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import context "context"
import core "github.com/lyft/flyteplugins/go/tasks/v1/pluginmachinery/core"
import mock "github.com/stretchr/testify/mock"

// EventsRecorder is an autogenerated mock type for the EventsRecorder type
type EventsRecorder struct {
	mock.Mock
}

// RecordRaw provides a mock function with given fields: ctx, ev
func (_m *EventsRecorder) RecordRaw(ctx context.Context, ev core.PhaseInfo) error {
	ret := _m.Called(ctx, ev)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, core.PhaseInfo) error); ok {
		r0 = rf(ctx, ev)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
