// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import flyteidlcore "github.com/lyft/flyteidl/gen/pb-go/flyteidl/core"
import mock "github.com/stretchr/testify/mock"

// TaskExecutionID is an autogenerated mock type for the TaskExecutionID type
type TaskExecutionID struct {
	mock.Mock
}

// GetGeneratedName provides a mock function with given fields:
func (_m *TaskExecutionID) GetGeneratedName() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// GetID provides a mock function with given fields:
func (_m *TaskExecutionID) GetID() flyteidlcore.TaskExecutionIdentifier {
	ret := _m.Called()

	var r0 flyteidlcore.TaskExecutionIdentifier
	if rf, ok := ret.Get(0).(func() flyteidlcore.TaskExecutionIdentifier); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(flyteidlcore.TaskExecutionIdentifier)
	}

	return r0
}
