// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// PluginContext is an autogenerated mock type for the PluginContext type
type PluginContext struct {
	mock.Mock
}
