// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import catalog "github.com/lyft/flyteplugins/go/tasks/pluginmachinery/catalog"
import mock "github.com/stretchr/testify/mock"

// DownloadFuture is an autogenerated mock type for the DownloadFuture type
type DownloadFuture struct {
	mock.Mock
}

// GetResponse provides a mock function with given fields:
func (_m *DownloadFuture) GetResponse() (catalog.DownloadResponse, error) {
	ret := _m.Called()

	var r0 catalog.DownloadResponse
	if rf, ok := ret.Get(0).(func() catalog.DownloadResponse); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(catalog.DownloadResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetResponseStatus provides a mock function with given fields:
func (_m *DownloadFuture) GetResponseStatus() catalog.ResponseStatus {
	ret := _m.Called()

	var r0 catalog.ResponseStatus
	if rf, ok := ret.Get(0).(func() catalog.ResponseStatus); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(catalog.ResponseStatus)
	}

	return r0
}
