// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import bitarray "github.com/lyft/flytestdlib/bitarray"

import mock "github.com/stretchr/testify/mock"

// DownloadResponse is an autogenerated mock type for the DownloadResponse type
type DownloadResponse struct {
	mock.Mock
}

// GetCachedCount provides a mock function with given fields:
func (_m *DownloadResponse) GetCachedCount() int {
	ret := _m.Called()

	var r0 int
	if rf, ok := ret.Get(0).(func() int); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}

// GetCachedResults provides a mock function with given fields:
func (_m *DownloadResponse) GetCachedResults() *bitarray.BitSet {
	ret := _m.Called()

	var r0 *bitarray.BitSet
	if rf, ok := ret.Get(0).(func() *bitarray.BitSet); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*bitarray.BitSet)
		}
	}

	return r0
}

// GetResultsSize provides a mock function with given fields:
func (_m *DownloadResponse) GetResultsSize() int {
	ret := _m.Called()

	var r0 int
	if rf, ok := ret.Get(0).(func() int); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}
